"""Open WebUI v0.11.3 の設定 API の応答の形。テストの偽物が使う。

キー名は公開ソース（backend/open_webui/routers/retrieval.py の get_rag_config・get_embedding_config、
routers/tasks.py の TASK_CONFIG_KEYS、main.py の /api/version）から写した。値はこの環境で読んだもの
（Phase 4 設計書「着手時に判明したこと」4・9）か既定値で、鍵の欄には記録に漏れていないかを見る目印を入れた。
"""
_RETRIEVAL_KEYS = (
    "RAG_TEMPLATE TOP_K BYPASS_EMBEDDING_AND_RETRIEVAL RAG_FULL_CONTEXT ENABLE_RAG_HYBRID_SEARCH "
    "ENABLE_RAG_HYBRID_SEARCH_ENRICHED_TEXTS TOP_K_RERANKER RELEVANCE_THRESHOLD HYBRID_BM25_WEIGHT "
    "CONTENT_EXTRACTION_ENGINE CONTENT_EXTRACTION_SUPPORTED_MEDIA_MIME_TYPES PDF_EXTRACT_IMAGES PDF_LOADER_MODE "
    "DATALAB_MARKER_API_KEY DATALAB_MARKER_API_BASE_URL DATALAB_MARKER_ADDITIONAL_CONFIG DATALAB_MARKER_SKIP_CACHE "
    "DATALAB_MARKER_FORCE_OCR DATALAB_MARKER_PAGINATE DATALAB_MARKER_STRIP_EXISTING_OCR "
    "DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION DATALAB_MARKER_FORMAT_LINES DATALAB_MARKER_USE_LLM "
    "DATALAB_MARKER_OUTPUT_FORMAT EXTERNAL_DOCUMENT_LOADER_URL EXTERNAL_DOCUMENT_LOADER_API_KEY "
    "EXTERNAL_DOCUMENT_LOADER_HEADERS TIKA_SERVER_URL TIKA_SERVER_VERSION DOCLING_SERVER_URL DOCLING_API_KEY "
    "DOCLING_PARAMS DOCUMENT_INTELLIGENCE_ENDPOINT DOCUMENT_INTELLIGENCE_KEY DOCUMENT_INTELLIGENCE_MODEL "
    "MISTRAL_OCR_API_BASE_URL MISTRAL_OCR_API_KEY MISTRAL_OCR_USE_BASE64 PADDLEOCR_VL_BASE_URL PADDLEOCR_VL_TOKEN "
    "MINERU_API_MODE MINERU_API_URL MINERU_API_KEY MINERU_API_TIMEOUT MINERU_PARAMS MINERU_FILE_EXTENSIONS "
    "RAG_RERANKING_MODEL RAG_RERANKING_ENGINE RAG_RERANKING_BATCH_SIZE RAG_EXTERNAL_RERANKER_URL "
    "RAG_EXTERNAL_RERANKER_API_KEY RAG_EXTERNAL_RERANKER_TIMEOUT TEXT_SPLITTER RAG_TOKENIZER_MODEL "
    "ENABLE_MARKDOWN_HEADER_TEXT_SPLITTER CHUNK_SIZE CHUNK_MIN_SIZE_TARGET CHUNK_OVERLAP FILE_MAX_SIZE FILE_MAX_COUNT "
    "FILE_IMAGE_COMPRESSION_WIDTH FILE_IMAGE_COMPRESSION_HEIGHT ALLOWED_FILE_EXTENSIONS "
    "ENABLE_GOOGLE_DRIVE_INTEGRATION ENABLE_ONEDRIVE_INTEGRATION"
).split()

RETRIEVAL_CONFIG = {
    "status": True,
    **{key: ("secret-" + key.lower() if key.endswith(("_KEY", "_TOKEN")) else None) for key in _RETRIEVAL_KEYS},
    "RAG_TEMPLATE": "### Task:\nRespond to the user query using the provided context ...",
    "TOP_K": 3,
    "BYPASS_EMBEDDING_AND_RETRIEVAL": False,
    "RAG_FULL_CONTEXT": False,
    "ENABLE_RAG_HYBRID_SEARCH": False,
    "TOP_K_RERANKER": 3,
    "RELEVANCE_THRESHOLD": 0.0,
    "HYBRID_BM25_WEIGHT": 0.5,
    "CONTENT_EXTRACTION_ENGINE": "",
    "RAG_RERANKING_MODEL": "",
    "RAG_RERANKING_ENGINE": "",
    "TEXT_SPLITTER": "",
    "ENABLE_MARKDOWN_HEADER_TEXT_SPLITTER": True,
    "CHUNK_SIZE": 1000,
    "CHUNK_MIN_SIZE_TARGET": 0,
    "CHUNK_OVERLAP": 100,
    "web": {"WEB_SEARCH_ENGINE": "", "YOUCOM_API_KEY": "secret-youcom"},
}

EMBEDDING_CONFIG = {
    "status": True,
    "RAG_EMBEDDING_ENGINE": "",
    "RAG_EMBEDDING_MODEL": "BAAI/bge-m3",
    "RAG_EMBEDDING_BATCH_SIZE": 1,
    "ENABLE_ASYNC_EMBEDDING": True,
    "RAG_EMBEDDING_CONCURRENT_REQUESTS": 0,
    "openai_config": {"url": "", "key": "secret-openai"},
    "ollama_config": {"url": "", "key": "secret-ollama"},
    "azure_openai_config": {"url": "", "key": "secret-azure", "version": ""},
}

TASK_CONFIG = {
    "TASK_MODEL": "",
    "TASK_MODEL_EXTERNAL": "",
    "TASK_MODEL_PARAMS": {},
    "TITLE_GENERATION_PROMPT_TEMPLATE": "",
    "IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE": "",
    "ENABLE_AUTOCOMPLETE_GENERATION": False,
    "AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH": -1,
    "AUTOCOMPLETE_GENERATION_PROMPT_TEMPLATE": "",
    "TAGS_GENERATION_PROMPT_TEMPLATE": "",
    "FOLLOW_UP_GENERATION_PROMPT_TEMPLATE": "",
    "ENABLE_FOLLOW_UP_GENERATION": True,
    "ENABLE_TAGS_GENERATION": True,
    "ENABLE_TITLE_GENERATION": True,
    "ENABLE_SEARCH_QUERY_GENERATION": True,
    "ENABLE_RETRIEVAL_QUERY_GENERATION": False,
    "QUERY_GENERATION_PROMPT_TEMPLATE": "",
    "TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE": "",
    "ENABLE_VOICE_MODE_PROMPT": True,
    "VOICE_MODE_PROMPT_TEMPLATE": "",
}

VERSION = {"version": "0.11.3", "deployment_id": ""}
